#!/usr/bin/env bash

image=${IMAGE?missing IMAGE}

sed 's/a\/b:c/'$(echo "${image}" | sed 's/\//\\\//')'/' deploy/kubernetes/extender.yaml > extender.yaml

kubectl delete -f extender.yaml
kubectl apply -f extender.yaml
